
language: node_js
node_js:
  - "14"

cache:
  directories:
    - ./node_modules

after_success:
  - cd client
  - npm install
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/client
  on:
    branch: master
