
language: node_js
node_js:
  - "14"

branches:
  only:
    - main

script:
  - echo "Omitiendo tests"

cache:
  directories:
    - ./node_modules

before_deploy:
  - cd client
  - npm install
  - npm run build --base-href="/angular-deploy-test/"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: client/dist/client
  on:
    branch: main
