
language: node_js
node_js:
  - "14"

branches:
  only:
    - main

script:
  - echo "Omitiendo tests"

cache:
  directories:
    - ./node_modules

before_deploy:
  - cd client
  - npm install
  - npm run build

deploy:
  provider: heroku
  skip_cleanup: true
  keep_history: true
  api_key: $HEROKU_KEY
  app: restaurantedonbolo
  local_dir: client/dist/client
  on:
    repo: Elsorbo/angular-deploy-test
    branch: main
